ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o

#
# Support for camera actuator by ZTE_JIA_20130729 jia.jia
#
obj-$(CONFIG_BU64291) += bu64291.o
obj-$(CONFIG_DW9714) += dw9714.o
